#!/bin/bash

if [[ $DISPLAY ]]
then
	get_display_1 () {
		xrandr | grep -w "connected" | awk 'FNR==1{print $1}'
	}
	get_display_2 () {
		xrandr | grep -w "connected" | awk 'FNR==2{print $1}'
	}

	value_1=get_display_1
	value_2=get_display_2

	if [[ $(get_display_2) ]]
	then
		xrandr --output $(eval $value_2) --left-of $(eval $value_1) --auto
	fi
fi
