[font]
size = 18

[font.normal]
family = "Fira Code"

[shell]
program = "/bin/bash"

[env]
WINIT_X11_SCALE_FACTOR = "1.66"

[keyboard]
bindings = [
	{ key = "Key6", mods = "Control", chars = "\u001e" }
]
