[font]
size = 12

[font.normal]
family = "Fira Code"

[terminal.shell]
program = "/bin/bash"

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[keyboard]
bindings = [
	{ key = "Key6", mods = "Control", chars = "\u001e" }
]
